import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

/*
  Generated class for the CityDataProvider provider.

  See https://angular.io/guide/dependency-injection for more info on providers
  and Angular DI.
*/
@Injectable()
export class ZhuanyeDataProvider {

  zhuanyes: any[];

  constructor() {
    this.zhuanyes = [{
      "options": [{
          "text": "哲学",
          "value": "01"
      }, {
          "text": "经济学",
          "value": "02"
      }, {
          "text": "法学",
          "value": "03"
      }, {
          "text": "教育学",
          "value": "04"
      }, {
          "text": "文学",
          "value": "05"
      }, {
          "text": "历史",
          "value": "06"
      }, {
          "text": "理学",
          "value": "07"
      }, {
          "text": "工学",
          "value": "08"
      }, {
          "text": "农学",
          "value": "09"
      }, {
          "text": "医学",
          "value": "10"
      }, {
          "text": "军事学",
          "value": "11"
      }, {
          "text": "管理学",
          "value": "12"
      }, {
          "text": "艺术学",
          "value": "13"
      }]
  },{
      "options": [{
          "text": "哲学",
          "value": "0101",
          "parentVal": "01"
      },{
          "text": "理论经济学",
          "value": "0201",
          "parentVal": "02"
      },{
          "text": "应用经济学",
          "value": "0202",
          "parentVal": "02"
      },{
          "text": "法学",
          "value": "0301",
          "parentVal": "03"
      }, {
          "text": "政治学",
          "value": "0302",
          "parentVal": "03"
      },{
          "text": "社会学",
          "value": "0303",
          "parentVal": "03"
      }, {
          "text": "民族学",
          "value": "0304",
          "parentVal": "03"
      },{
          "text": "马克思主义理论",
          "value": "0305",
          "parentVal": "03"
      },{
          "text": "教育学",
          "value": "0401",
          "parentVal": "04"
      },{
          "text": "心理学",
          "value": "0402",
          "parentVal": "04"
      }, {
          "text": "体育学",
          "value": "0403",
          "parentVal": "04"
      },{
          "text": "中国语言学",
          "value": "0501",
          "parentVal": "05"
      }, {
          "text": "外国语言文学",
          "value": "0502",
          "parentVal": "05"
      },{
          "text": "新闻传播学",
          "value": "0503",
          "parentVal": "05"
      },{
          "text": "历史学",
          "value": "0601",
          "parentVal": "06"
      },{
          "text": "数学",
          "value": "0701",
          "parentVal": "07"
      },{
          "text": "物理学",
          "value": "0702",
          "parentVal": "07"
      },{
          "text": "化学",
          "value": "0703",
          "parentVal": "07"
      }, {
          "text": "天文学",
          "value": "0704",
          "parentVal": "07"
      }, {
          "text": "地理学",
          "value": "0705",
          "parentVal": "07"
      }, {
          "text": "大气科学",
          "value": "0706",
          "parentVal": "07"
      }, {
          "text": "海洋科学",
          "value": "0707",
          "parentVal": "07"
      }, {
          "text": "地球物理学",
          "value": "0708",
          "parentVal": "07"
      }, {
          "text": "地质学",
          "value": "0709",
          "parentVal": "07"
      }, {
          "text": "生物学",
          "value": "0710",
          "parentVal": "07"
      }, {
          "text": "系统科学",
          "value": "0711",
          "parentVal": "07"
      }, {
          "text": "科学技术史",
          "value": "0712",
          "parentVal": "07"
      }, {
          "text": "力学",
          "value": "0801",
          "parentVal": "08"
      }, {
          "text": "机械工程",
          "value": "0802",
          "parentVal": "08"
      }, {
          "text": "光学工程",
          "value": "0803",
          "parentVal": "08"
      }, {
          "text": "仪器科学与技术",
          "value": "0804",
          "parentVal": "08"
      }, {
          "text": "材料科学与工程",
          "value": "0805",
          "parentVal": "08"
      }, {
          "text": "冶金工程",
          "value": "0806",
          "parentVal": "08"
      }, {
          "text": "动力工程及工程热物理",
          "value": "0807",
          "parentVal": "08"
      }, {
          "text": "电气工程",
          "value": "0808",
          "parentVal": "08"
      }, {
          "text": "电子科技与技术",
          "value": "0809",
          "parentVal": "08"
      }, {
          "text": "信息与通信工程",
          "value": "0810",
          "parentVal": "08"
      }, {
          "text": "控制科学与工程",
          "value": "0811",
          "parentVal": "08"
      }, {
          "text": "计算机科学与技术",
          "value": "0812",
          "parentVal": "08"
      }, {
          "text": "建筑学",
          "value": "0813",
          "parentVal": "08"
      }, {
          "text": "土木工程",
          "value": "0814",
          "parentVal": "08"
      }, {
          "text": "水利工程",
          "value": "0815",
          "parentVal": "08"
      }, {
          "text": "测绘科学与技术",
          "value": "0816",
          "parentVal": "08"
      }, {
          "text": "化学工程与技术",
          "value": "0817",
          "parentVal": "08"
      }, {
          "text": "地质资源与地质工程",
          "value": "0818",
          "parentVal": "08"
      }, {
          "text": "矿业工程",
          "value": "0819",
          "parentVal": "08"
      }, {
          "text": "石油与天然气工程",
          "value": "0820",
          "parentVal": "08"
      }, {
          "text": "纺织科学与工程",
          "value": "0821",
          "parentVal": "08"
      }, {
          "text": "轻工技术与工程",
          "value": "0822",
          "parentVal": "08"
      }, {
          "text": "交通运输工程",
          "value": "0823",
          "parentVal": "08"
      }, {
          "text": "船舶与海洋工程",
          "value": "0824",
          "parentVal": "08"
      }, {
          "text": "航空宇航科学与技术",
          "value": "0825",
          "parentVal": "08"
      }, {
          "text": "兵器科学技术",
          "value": "0826",
          "parentVal": "08"
      }, {
          "text": "核科学与技术",
          "value": "0827",
          "parentVal": "08"
      }, {
          "text": "农业工程",
          "value": "0828",
          "parentVal": "08"
      }, {
          "text": "林业工程",
          "value": "0829",
          "parentVal": "08"
      }, {
          "text": "环境科学与工程",
          "value": "0830",
          "parentVal": "08"
      }, {
          "text": "生物医学工程",
          "value": "0831",
          "parentVal": "08"
      }, {
          "text": "食品科学与工程",
          "value": "0832",
          "parentVal": "08"
      }, {
          "text": "作物学",
          "value": "0901",
          "parentVal": "09"
      }, {
          "text": "园艺学",
          "value": "0902",
          "parentVal": "09"
      }, {
          "text": "农业资源利用",
          "value": "0903",
          "parentVal": "09"
      }, {
          "text": "植物保护",
          "value": "0904",
          "parentVal": "09"
      }, {
          "text": "畜牧学",
          "value": "0905",
          "parentVal": "09"
      }, {
          "text": "林学",
          "value": "0906",
          "parentVal": "09"
      }, {
          "text": "水产",
          "value": "0907",
          "parentVal": "09"
      }, {
          "text": "基础医学",
          "value": "1001",
          "parentVal": "10"
      }, {
          "text": "临床医学",
          "value": "1002",
          "parentVal": "10"
      }, {
          "text": "口腔医学",
          "value": "1003",
          "parentVal": "10"
      }, {
          "text": "公共卫生与预防医学",
          "value": "1004",
          "parentVal": "10"
      }, {
          "text": "中医学",
          "value": "1005",
          "parentVal": "10"
      }, {
          "text": "基础中医学",
          "value": "10051",
          "parentVal": "10"
      }, {
          "text": "临床中医学",
          "value": "10052",
          "parentVal": "10"
      }, {
          "text": "中西医结合",
          "value": "1006",
          "parentVal": "10"
      }, {
          "text": "药学",
          "value": "1007",
          "parentVal": "10"
      }, {
          "text": "中药学",
          "value": "1008",
          "parentVal": "10"
      }, {
          "text": "军事思想及军事历史",
          "value": "1101",
          "parentVal": "11"
      }, {
          "text": "战略学",
          "value": "1102",
          "parentVal": "11"
      }, {
          "text": "战役学",
          "value": "1103",
          "parentVal": "11"
      }, {
          "text": "战术学",
          "value": "1104",
          "parentVal": "11"
      }, {
          "text": "军队指挥学",
          "value": "1105",
          "parentVal": "11"
      }, {
          "text": "军制学",
          "value": "1106",
          "parentVal": "11"
      }, {
          "text": "军队政治工作",
          "value": "1107",
          "parentVal": "11"
      }, {
          "text": "军事后勤学与军事装备学",
          "value": "1108",
          "parentVal": "11"
      }, {
          "text": "管理科学与工程",
          "value": "1201",
          "parentVal": "12"
      }, {
          "text": "工商管理",
          "value": "1202",
          "parentVal": "12"
      }, {
          "text": "农林经济管理",
          "value": "1203",
          "parentVal": "12"
      }, {
          "text": "公共管理",
          "value": "1204",
          "parentVal": "12"
      }, {
          "text": "图书馆、情报与档案管理",
          "value": "1205",
          "parentVal": "12"
      }, {
          "text": "艺术学",
          "value": "1301",
          "parentVal": "13"
      }]
    }]
  }
}
